:PROPERTIES:
:ID:       e4963fac-4f3a-46f5-8b69-e581195aa4f0
:END:
#+title: translate "Un año de la pandemia: opacidad en los gastos y una reforma tributaria para pagarlos"
* translated
# A year of opaque pandemic spending, and a tax reform to pay for it

After the one-year anniversary of Colombia's announced state of emergency due to the pandemic, where have the more than 40 trillion pesos earmarked for it been spent? The Observatorio Fiscal de la Javeriana has been investigating, and found more questions than answers.

How should one measure the cost of the Covid-19 pandemic to Colombia? Foremost is we should consider the loss of 61,143 lives and the application of 782,0301 [[Something is wrong with that number. But moreover, how are vaccines a cost? Weren't a lot of them free? --jbb]] vaccines, per [[citation?]] reports on March 13th and 14th of this year, respectively. The consequences, however, extend beyond public health. 2020 ended with an unemployment rate of 15.9%, and 3.7 million Colombians began 2021 unemployed. [[This is confusing. Those are presented as if they are two different things, but they're the same figure, right? --jbb]]

Colombians' purchasing power has fallen. This has been driven in part by the [[suspension? closure? --jbb]] of more than half a million small businesses, and for a mandatory pause in the activities of a substantial portion of the services sector. The result has been a fall in GDP of 6.8%, the biggest for which records exist -- worse than the crisis of 1999, and worse even than the Great Depression of the 1930s.

Clearly, one cannot capture in a single statistic the consequences of an emergency that has so dramatically changed our daily habits and impacted key dimensions of well-being such as household living, the care economy, mental health.

Evaluating the pandemic's consequences and building a roadmap toward recovery, principally economic recovery, is critical. However, so too is a less commonly discussed concern: Repairing citizens' confidence in their institutions, their government, and the people that constitute them.

Over the past year, we at the Observatorio Figure de la Universidad Javeriana have followed the use of public resources devoted to the health emergency. This is important. Knowing how public resources are used is key to addressing the problems the pandemic has brought, from maintaining public health to limiting economic fallout.

How much money has been spent? Which sectors, entities and programs did it go to? When? It is our worrying conclusion that, after a year, there is no detailed way to know. Moreover, there is still no detailed plan for the trillions of pesos aimed at the pandemic that have been budgeted but not yet spent.

Massive, opaque spending does not imply theft, but it is gravely serious. It is illegal, a violation of Colombia's Ley de Transparencia y Responsabilidad Fiscal. It is the reason Colombia did not grant broad, meaningful wage subsidies -- something that resulted in a massive rise in unemployment. It will soon lead to a sharp rise in taxes.


# Investigating pandemic-related measures

At the beginning of the pandemic, the Observatorio Fiscal suggested [[citation?]] policies to mitigate its impact, emphasizing measures to protect vulnerable families, businesses at risk of bankruptcy and workers at risk of becoming unemployed.

Later, we evaluated [[citation?]] a policy [[that already existed? that was being considered? --jbb]] of reimbursing the VAT paid by the least wealthy Colombians, as described in the [[Congressional?]] document CONPES 3986. The VAT reimbursement program, which refunded between 70 and 80 thousand pesos to poor families, was initially conceived as a measure to be expanded over time, and indeed it reamped up over the course of the pandemic. In 2020 it reached a million people [[not families?]], and this year is expected to reach twice as many.

Congress will debate tax reform in two weeks. One proposal to be discussed then is that VAT exemptions for basic household essentials are not a fairness measure but rather a tax benefit. [[I don't know what this next sentence means: El argumento es que ese eventual pago adicional de IVA ya se les está compensando a los colombianos más pobres.]]

Nevertheless, the VAT rebate, which is anticipated to devolve 2 trillion pesos to Colombia's poorest 20%, pale in comparison with the tax benefits that go to the richest 1%. The latter, approved in the tax reform of 2018, total nearly 9 trillion pesos. (Details below.)

After analyzing the VAT rebate, we produced a preliminary evaluation of the national government's response to the pandemic. Our conclusion was that, in addition to losing jobs and businesses, the government's slow response would make the economic recovery unnecessarily slow.

[[I need someone to explain what this 80-word sentence means to me before I can translate it. "Posteriormente hicimos una compilación de las políticas económicas implementadas –un ejercicio que también llevamos a cabo para la segunda declaratoria de Estado de Emergencia–, una evaluación de las medidas con impacto regional adoptadas desde el orden nacional y una centralización de las nueve políticas de transferencias monetarias directas y extraordinarias que se pusieron en marcha. Este último informe encontró que no hay montos detallados sobre algunas de estas transferencias o información puntual sobre los requisitos o destinatarios de algunos dineros."]]

There is a debate in Colombia over the need for and feasibility of a national basic income -- one that has been especially active since the 2022 presidential election. We published a report computing the cost of such a program.

We also analyzed and reported [[citation]] on Colombians' capacity to save, discovering that savings is a luxury out of reach for around half the population.


# Following the money

In the course of the work described above, we developed tools that let us analyze where pandemic-related funds went.

* untranslated

El decreto 444 de 2020 creó el Fondo de Mitigación de Emergencias (FOME) estableció sus fuentes de financiación, pero no especificó montos. Para conocerlos hubo que consultar los 331 decretos expedidos al amparo de la emergencia. Ninguno de ellos especificaba desde dónde se estaba girando el dinero. Para saber a qué entidades se estaban girando los recursos fue necesario consultar una por una las resoluciones.

Luego había que rastrear los gastos por contratación. En este sentido, el Portal de Transparencia Económica del Ministerio de Hacienda brinda un formato uniforme y fácil de procesar. Sin embargo, encontramos que en ese momento –junio de 2020, uno de los momentos más dramáticos de la emergencia– la mayor parte de los fondos de emergencia no se habían utilizado.

Navegar cientos de decretos, resoluciones, contratos, declaraciones de funcionarios a medios de comunicación e intervenciones legislativas tomó, en suma, 26 días y medio. Nosotros felices, pero, ¿cuántos ciudadanos de a pie tienen el tiempo o el conocimiento para adelantar una tarea de esta naturaleza?

Esta ruta, más simplificada, es la que hemos seguido a lo largo de estos meses para reportar periódicamente cómo avanza el gasto de la plata dispuesta para la pandemia.

Varios de los problemas iniciales –como la ausencia de centralización sobre los decretos expedidos al amparo de la emergencia, el poco nivel de detalle en las transferencias de dinero y el carácter excesivamente general de muchos contratos– persisten. Sin embargo, es importante destacar avances en la presentación de información completa y entendible para los ciudadanos, como los que muestran el Portal de Transparencia Económica y el sitio de Presupuesto Emergencia COVID-19 del Ministerio de Hacienda.

Nadie estaba preparado para una pandemia, y hasta cierto punto es comprensible que durante los primeros meses la información sobre un andamiaje normativo e institucional creado en cuestión de días no tuviera la capacidad de presentar la información de forma completa y comprensible para todos. Sin embargo, pasado un año, muchos de esos problemas se mantienen.

Entonces, ¿cuánta plata se ha gastado?
Nuestros hallazgos dan cuenta de lo siguiente: con corte al 4 de marzo, el FOME cuenta con un presupuesto de $40,5 billones –o millones de millones– de pesos. Hasta esa fecha se habían desembolsado $29,7 billones de pesos desde el fondo.

De esos recursos, $14,4 billones se trasladaron a cuentas creadas exclusivamente para programas de la emergencia. Es posible identificar, además, que 10,8 billones han sido comprometidos y 9,7 billones han sido pagados. No obstante, hay otros 6,8 billones de pesos que fueron transferidos a otras cuentas, y no es posible identificar su nivel de compromiso o pago.

Es posible saber también que desde el Ministerio de Hacienda se han comprometido $8,5 billones de pesos, de los cuales se ha pagado el 84 %. Sin embargo, la información disponible no permite saber cuántos recursos han sido apropiados por esta cartera para los programas a su cargo.

La conclusión es que, como lo señalamos antes, pasado un año desde la declaración del Estado de Emergencia, no es posible conocer el destino específico de los recursos utilizados, lo cual se suma a la falta de un plan de gasto detallado –peso por peso y no billón por billón– que permita saber en qué se ha gastado toda la plata.

Si no tenemos toda la información ¿es posible diseñar políticas exitosas que promuevan la recuperación del empleo y la generación de nuevos puestos de trabajo?
El camino por venir
Además de contrariar parte de lo ordenado por la Ley de Transparencia y de acentuar la desconfianza ciudadana en los administradores de los recursos públicos, este nivel de opacidad tiene una consecuencia adicional –todavía más grave–: esta plata, sepamos o no exactamente en qué se gastó, la tendremos que pagar todos los colombianos.

Buena parte de los recursos del FOME provienen de un rubro denominado deuda. Esto implica que lo que se gaste hoy tendrá que pagarse mañana, acudiendo a nuevas fuentes. Como si fuera una tarjeta de crédito, los próximos gobiernos tendrán que acudir a otras fuentes de financiación para obtener esos recursos.

Sin embargo, es casi imposible planear políticas económicas estables si no se cuenta con información completa. Esto plantea un panorama especialmente complejo si se tiene en cuenta que el gasto realizado durante la pandemia se concentró en sectores estratégicos para el presente y el futuro del país –como la salud, el empleo y la política social–.

Si no tenemos toda la información sobre la inversión en programas de ayuda a sectores productivos, ¿es posible diseñar políticas exitosas que promuevan la recuperación del empleo y la generación de nuevos puestos de trabajo?

No es claro, por ejemplo, el enfoque y el énfasis que deberían tener las políticas orientadas a combatir la pobreza y la pobreza extrema en el país. La razón es que la nueva reforma tributaria –cuyos ejes centrales al parecer serán la eliminación de las exenciones de IVA, sin aumentar los impuestos de los grandes capitales– toca directamente el bolsillo de la clase media colombiana.

Resulta innegable que, de cara a la recuperación económica, todos tendremos que hacer sacrificios, pero no es claro por qué la mayor parte de la carga se quiere poner sobre los trabajadores que viven de su sueldo –no solo quienes ganan cinco o seis salarios mínimos, sino también los que ganan uno o dos, y que no están cubiertos por los programas sociales del Estado–.

Saber cómo se ha gastado y cómo se planea gastar la plata de todos debe ser la regla, no la excepción. Buscar esa información no tendría que ser una odisea burocrática para la ciudadanía. Entre otras cosas, la ley establece que el Gobierno no solo debe dar respuesta a las preguntas de los ciudadanos, sino que debe ser proactivo en la divulgación de la información sobre el uso de los recursos públicos.

El acceso a la información sobre el gasto público no debería ser un privilegio de burócratas y especialistas, sino que tiene que estar al alcance de todos. Hagamos fuerza para que en este cumpleaños de la pandemia ese deseo se haga realidad.
