:PROPERTIES:
:ID:       529da23b-382f-46cf-908f-7d8941ca865a
:END:
#+title: who the Observatorio is: essay(s)
* 2, Jeff paring it down
En el 2018 lanzó el Observatorio Fiscal, motivado por la brecha entre la importancia de la transparencia en el gasto público, y la desconfianza generalizada de la ciudadanía sobre la información relacionada con este. Fuimos el primer centro de pensamiento de política fiscal independiente del Gobierno nacional, de los gremios, o de los intereses particulares de quienes administran los recursos públicos.

Analizamos el gasto público y las propuestas de reforma tributaria, enfocándo en los efectos sobre la distribución del ingreso, la riqueza y el crecimiento económico, y su impacto en las mujeres. Apoyamos a los medios de comunicación para fortalecer su entendimiento del efecto de las políticas fiscales sobre la equidad y el crecimiento económico. Comunicamos con la ciudadanía en un lenguaje claro, sencillo y entendible a través de su blog, redes sociales, guías ciudadanas, y la organización de eventos, conversatorios y foros sobre política fiscal. Producimos análisis de calidad para que los diseñadores de política pública tengan a su disposición la mejor información posible a la hora de tomar decisiones.

Nuestros públicos objetivo son los medios de comunicación (periodistas económicos, productores, editores, jefes de redacción, reporteros y comunicadores independientes), el Congreso de la República (senadores, representantes a la Cámara, equipos técnicos o las Unidades de Trabajo Legislativo -conocidas como UTL, secretarías y oficinas de comunicaciones de ambas cámaras) y la ciudadanía en general.

El Observatorio Fiscal está conformado por un grupo de diez profesionales de distintas disciplinas, del cual hace parte Oliver Pardo (actual director), Jeff Brown (director tecnológico), William Reyes (asesor de finanzas públicas), Alejandro Gómez (director de comunicaciones), Angélica Nieto (analista de política fiscal), Daniel Duque (subdirector de analítica e inteligencia artificial), Angélica Vargas (analista financiera), Manuela Ospina (diseñadora gráfica), Mauricio Salazar (investigador) y Juan Miguel Villa (investigador y miembro honorario).

El OF ha logrado conseguir importantes menciones en el Congreso de la República, liderar iniciativas en contra de las reformas tributarias regresivas del gobierno nacional, intervenir ante las comisiones económicas del Congreso, hacerle seguimiento a los recursos dispuestos para atender las consecuencias de la pandemia por medio de la creación de una plataforma web y la publicación de diferentes análisis del gasto, realizar y promover espacios de socialización de los análisis producidos en materia de tributación y uso de recursos públicos, dirigidos a la ciudadanía y a los medios de comunicación.

El OF analizó, por ejemplo, cómo la falta de transparencia presupuestal y las medidas tributarias regresivas que propuso en 2021 el Ministerio de Hacienda y Crédito Público (principal administrador de los recursos públicos) incrementaron la desconfianza de la ciudadanía y generaron un descontento generalizado, el cual terminó en un paro nacional marcado por una de las jornadas de manifestaciones más violentas de los últimos años, el cual dejó más de 80 víctimas mortales y más de 2000 heridos, según cifras de Indepaz. Esta situación, aunque se refiere exclusivamente a Colombia, es fácilmente extrapolable al contexto latinoamericano, donde muchos de los problemas de desarrollo económico están ligados a la ausencia de información clara, o a la oportunidad limitada que tienen los ciudadanos de basar sus decisiones de participación en información técnica y actualizada.

La experiencia del Observatorio Fiscal ha permitido generar lecciones útiles en la democratización de la información de las finanzas públicas que contribuyen a resolver los dilemas relacionados con el desarrollo económico. Igualmente, este centro de pensamiento siempre está en la búsqueda constante de nuevas acciones efectivas y oportunidades de mejora para seguir poniendo la información de las finanzas públicas -especialmente la relacionada con la tributación y el gasto público- al alcance de todas y todos los colombianos.
* 1, Alejandro
** source (an email)
   https://mail.google.com/mail/u/0/#inbox/QgrcJHsTfQzCXMzBTvxWpqLMDDctXPsMScb
** the essay
A medida que pasa el tiempo, la necesidad de la ciudadanía por conocer el uso de los recursos públicos en Colombia aumentó como resultado de procesos comprobados de corrupción y un mayor interés en la toma de decisiones económicas por parte de los votantes, así como por el aumento en el control político de los diferentes partidos presentes en el escenario nacional. Es así como, la necesidad y el interés creciente de la ciudadanía por saber cómo se gastan estos recursos y cuáles son los planes que tiene el gobierno en la materia, se debe en gran medida a que los administradores no han sido lo suficientemente transparentes, proactivos ni claros al presentar esta información a la ciudadanía, incumpliendo con la Ley de Transparencia y del Derecho de Acceso a la Información Pública Nacional, Ley 1712 de 2014, que consagra la transparencia y el acceso a la información pública como un derecho fundamental para conocer de la existencia y acceder a la información pública en posesión o control de los sujetos obligados (Procuraduría General de la Nación, 2009). Aún con esta necesidad sentida, hasta 2018 no existía un centro de pensamiento de política fiscal independiente del Gobierno nacional, de los gremios, o de los intereses particulares de quienes administran los recursos públicos, motivo por el cual, desde la PUJ, particularmente la Facultad de Ciencias Económicas y Administrativas, se planteó la necesidad de llenar esta brecha entre la importancia de la transparencia en el gasto público, y la desconfianza generalizada de la ciudadanía sobre la información relacionada con este.



Es así como, en abril de 2018, se crea el Observatorio Fiscal de la Pontificia Universidad Javeriana, con el objetivo principal de democratizar la información sobre las finanzas públicas en Colombia. Este centro de pensamiento (A) analiza el gasto público y las propuestas de reforma tributaria, enfocándose en los efectos sobre la distribución del ingreso, la riqueza y el crecimiento económico, y su impacto en las mujeres. (B) Apoya a los medios de comunicación para fortalecer su entendimiento del efecto de las políticas fiscales sobre la equidad y el crecimiento económico. (C) Se comunica con la ciudadanía en un lenguaje claro, sencillo y entendible a través de su blog, redes sociales, guías ciudadanas, y la organización de eventos, conversatorios y foros sobre política fiscal. (D) produce análisis de calidad para que los diseñadores de política pública tengan a su disposición la mejor información posible a la hora de tomar decisiones. Por esto, sus públicos objetivo son los medios de comunicación (periodistas económicos, productores, editores, jefes de redacción, reporteros y comunicadores independientes), el Congreso de la República (senadores, representantes a la Cámara, equipos técnicos o las Unidades de Trabajo Legislativo -conocidas como UTL, secretarías y oficinas de comunicaciones de ambas cámaras) y la ciudadanía en general, donde se encuentran tanto un público especialista (academia, expertos, analistas, investigadores y otros centros de investigación) como uno no especialista (ciudadanos no expertos en temas de finanzas públicas).



El Observatorio Fiscal está conformado por un grupo de diez profesionales de distintas disciplinas, del cual hace parte Oliver Pardo (actual director), Jeff Brown (director tecnológico), William Reyes (asesor de finanzas públicas), Alejandro Gómez (director de comunicaciones), Angélica Nieto (analista de política fiscal), Daniel Duque (subdirector de analítica e inteligencia artificial), Angélica Vargas (analista financiera), Manuela Ospina (diseñadora gráfica), Mauricio Salazar (investigador) y Juan Miguel Villa (investigador y miembro honorario).



Dentro de sus estrategias de comunicación, el OF organiza y promueve espacios de participación ciudadana para que los colombianos conozcan de primera mano lo que ocurre en el país en materia económica, especialmente en materia de gasto público y tributación, organizando espacios virtuales y presenciales con diferentes actores (congresistas, funcionarios públicos de entidades y ministerios, académicos, investigadores, organizaciones civiles, periodistas) y la ciudadanía en general. Práctica que ha permitido, entre otras cosas, generar interés en el público general sobre el gasto público en el país, alentando a las instituciones a fortalecer sus sistemas de rendición de cuentas. Es decir, más actores interesados reclamando información y sistemas de información estatales que se reconocieron como limitados o complejos.



Durante los últimos cuatro años, el OF ha pretendido llenar los vacíos de información acerca del uso de los recursos públicos - obligación de los funcionarios del Gobierno nacional, responsables de esta labor- evidenciando los problemas de la ciudadanía para acceder y conocer la información de las finanzas públicas.



image.png



El OF ha logrado conseguir importantes menciones en el Congreso de la República, liderar iniciativas en contra de las reformas tributarias regresivas del Gob. nacional, intervenir ante las comisiones económicas del Congreso, hacerle seguimiento a los recursos dispuestos para atender las consecuencias de la pandemia por medio de la creación de una plataforma web y la publicación de diferentes análisis del gasto, realizar y promover espacios de socialización de los análisis producidos en materia de tributación y uso de recursos públicos, dirigidos a la ciudadanía y a los medios de comunicación.



El OF analizó, por ejemplo, cómo la falta de transparencia presupuestal y las medidas tributarias regresivas que propuso en 2021 el Ministerio de Hacienda y Crédito Público (principal administrador de los recursos públicos) incrementaron la desconfianza de la ciudadanía y generaron un descontento generalizado, el cual terminó en un paro nacional marcado por una de las jornadas de manifestaciones más violentas de los últimos años, el cual dejó más de 80 víctimas mortales y más de 2000 heridos, según cifras de Indepaz. Esta situación, aunque se refiere exclusivamente a Colombia, es fácilmente extrapolable al contexto latinoamericano, donde muchos de los problemas de desarrollo económico están ligados a la ausencia de información clara, o a la oportunidad limitada que tienen los ciudadanos de basar sus decisiones de participación en información técnica y actualizada.



La experiencia del Observatorio Fiscal ha permitido generar lecciones útiles en la democratización de la información de las finanzas públicas que contribuyen a resolver los dilemas relacionados con el desarrollo económico. Igualmente, este centro de pensamiento siempre está en la búsqueda constante de nuevas acciones efectivas y oportunidades de mejora para seguir poniendo la información de las finanzas públicas -especialmente la relacionada con la tributación y el gasto público- al alcance de todas y todos los colombianos.
